#!/bin/bash

sudo pacman -Syyyuuu --needed --noconfirm
sudo pacman -S --needed --noconfirm git

rm -rf ./dotfiles
git clone https://github.com/chunix64/dotfiles
cd ./dotfiles/scripts
bash ./install.sh
